# Generated by Django 6.0.2 on 2026-03-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
