# Generated by Django 6.0.2 on 2026-03-29 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicecenter_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія сервісу',
                'verbose_name_plural': 'Категорії сервісів',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicecenter',
            options={'ordering': ['name'], 'verbose_name': 'Сервісний центр', 'verbose_name_plural': 'Сервісні центри'},
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='Години роботи'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='ServiceCenterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_centers/', verbose_name='Фото')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Опис фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.servicecenter', verbose_name='Сервісний центр')),
            ],
            options={
                'verbose_name': 'Фото сервісного центру',
                'verbose_name_plural': 'Фото сервісних центрів',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис послуги')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна від')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.servicecategory', verbose_name='Категорія')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.servicecenter', verbose_name='Сервісний центр')),
            ],
            options={
                'verbose_name': 'Послуга сервісного центру',
                'verbose_name_plural': 'Послуги сервісних центрів',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.servicecenter', verbose_name='Сервісний центр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Обране',
                'verbose_name_plural': 'Обране',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'service_center')},
            },
        ),
    ]
