# Generated by Django 6.0.2 on 2026-04-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecenterimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Фото сервісного центру', 'verbose_name_plural': 'Фото сервісних центрів'},
        ),
        migrations.RemoveField(
            model_name='servicecenterimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='servicecenterimage',
            name='is_main',
        ),
    ]
