# Generated by Django 6.0.2 on 2026-04-15 20:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_servicecenterimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenterimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото'),
        ),
    ]
