# Generated by Django 6.0.2 on 2026-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_servicecenterimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='servicecenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота'),
        ),
    ]
