# Generated by Django 6.0.2 on 2026-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicecenter_latitude_servicecenter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Довгота'),
        ),
    ]
