# Generated by Django 6.0.2 on 2026-04-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_servicecenter_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True, verbose_name='Довгота'),
        ),
    ]
