# Generated by Django 6.0.2 on 2026-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_servicecenter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='district',
            field=models.CharField(blank=True, choices=[('holosiivskyi', 'Голосіївський'), ('darnytskyi', 'Дарницький'), ('desnianskyi', 'Деснянський'), ('dniprovskyi', 'Дніпровський'), ('obolonskyi', 'Оболонський'), ('pecherskyi', 'Печерський'), ('podilskyi', 'Подільський'), ('sviatoshynskyi', 'Святошинський'), ('solomianskyi', 'Солом’янський'), ('shevchenkivskyi', 'Шевченківський')], max_length=50, verbose_name='Район'),
        ),
    ]
