# Generated by Django 6.0.2 on 2026-04-23 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicecenter_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('district', models.CharField(blank=True, choices=[('holosiivskyi', 'Голосіївський'), ('darnytskyi', 'Дарницький'), ('desnianskyi', 'Деснянський'), ('dniprovskyi', 'Дніпровський'), ('obolonskyi', 'Оболонський'), ('pecherskyi', 'Печерський'), ('podilskyi', 'Подільський'), ('sviatoshynskyi', 'Святошинський'), ('solomianskyi', 'Солом’янський'), ('shevchenkivskyi', 'Шевченківський')], max_length=50, verbose_name='Район')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='Години роботи')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True, verbose_name='Довгота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Заявка на додавання сервісу',
                'verbose_name_plural': 'Заявки на додавання сервісів',
                'ordering': ['-created_at'],
            },
        ),
    ]
