# Generated by Django 6.0.2 on 2026-04-23 18:55

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_servicecentersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecentersubmission',
            name='services_note',
            field=models.TextField(blank=True, verbose_name='Послуги сервісу'),
        ),
        migrations.CreateModel(
            name='ServiceCenterSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.servicecentersubmission', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
                'ordering': ['created_at'],
            },
        ),
    ]
